### ISSUE TITLE
Empty archive

### ISSUE THREAD

**Issue by Eldakhan** [steeno/EU4ConsolePatcher#1]
Hi Steeno and thanks for your work!

Just wanted to say that the pre-compiled EU4ConsolePatcher-Release-x64-static-v1.0.4.zip and
EU4ConsolePatcher-Release-x86-static-v1.0.4.zip appear to be empty. I can't seem to unzip them.

Have a good day. :)

**Comment by steeno** [comment]
Hi Eldakhan, i downloaded the archives too and can't reproduce your issue directly. But i figured out that the file extension was wrong. I copied the filename of the old releases, but didn't switched to zip-archive mode during archive creation. So the files were called xyz.zip but they were originally 7z-archives. I uploded real zip archives now and corrected the extension of the 7z-archives. So at least the new zip-archives should work on your site now.

**Comment by Eldakhan** [comment]
Ok, it works perfectly, thanks ! :)

**Comment by gearboros** [comment]
I had the same issue but since I managed to extract it with 7zip I though the problem was on my end.

**Comment by steeno** [comment]
Sorry for the circumstances and thanks for the information about the issue. So from now on everyone should be able to download and extract the archives without problems.
