### ISSUE TITLE
First memory pattern could not be found (Game Pass)

### ISSUE THREAD

**Issue by devve21** [steeno/EU4ConsolePatcher#10]
I am using the game pass version and the .exe file gives me this:
Trying to find module eu4.exe
eu4.exe module found
Trying to find memory patterns
First memory pattern could not be found

**Comment by steeno** [comment]
Hi @devve21
i will look into it sometime this day, thanks for mentioning this issue.

**Comment by steeno** [comment]
@devve21 could u download the newest release from https://github.com/steeno/EU4ConsolePatcher/releases/tag/v1.30.4.2 and try again?
