### ISSUE TITLE
First memory pattern could not be found (EU4 version 1.31.3)

### ISSUE THREAD

**Issue by NLangeweg** [steeno/EU4ConsolePatcher#12]
I've been trying to get this to work. I used the precompiled version and compiled the latest version of the EU4ConsolePatcher (v1.30.4.2) myself but no memory pattern could be found.

I'm using Windows 10 and got EU4 from steam. I'm using the latest EU4 version _1.31.3._

This is the console output of the release x64 build
```
Trying to find process eu4.exe
eu4.exe process found
Trying to find module eu4.exe
eu4.exe module found
Trying to find memory patterns
First memory pattern could not be found
Press any key to continue . . .
```

This is the console output of the debug x64 build
```
Trying to enable debug privileges for the current process
Debug privileges enabled
Trying to find process eu4.exe
process name: [System Process]
process name: System
process name: Registry
process name: smss.exe
process name: csrss.exe
process name: wininit.exe
...
  removed most process names because they where not necessary and to reduce the length of this post
...
process name: cmd.exe
process name: conhost.exe
process name: chrome.exe
process name: chrome.exe
process name: eu4.exe
th32ProcessID: 0x402c
th32ModuleID: 0x0
eu4.exe process found
Trying to find module eu4.exe
module name: eu4.exe
modBaseAddress: 0x7ff690460000
modBaseSize: 0x26ec000
eu4.exe module found
Trying to find memory patterns
processHandle: 0x00000000000000B4
BaseAddress: 0x00007FF690460000
RegionSize: 0x1000
PageSize: 0x1000
bytesRead: 26ec000
pattern: 74 ?? C6 44 24 28 00 41 B8 35 00 00 00
offset: 0x0
Pattern not found
First memory pattern could not be found
```

If you need more information or log files let me know.

Update:
I've tested the EU4ConsolePatcher on an older version of EU4 (1.30.1) and here it worked just fine. I'll start looking for the EU4 version where it stopped working

**Comment by steeno** [comment]
@NLangeweg : Hi, i was relatively sure that i also tested it on 1.31.3 some days ago, and it worked i thought xD, but i will double check it now. Will probably provide you with an update in some minutes. Just need to upgrade from 1.30.6 again. Thanks for the report mate. Don't think that dlc's matter, but do you also have all major expansions?

**Comment by NLangeweg** [comment]
@steeno I'm really confused. i just tried all versions from 1.30 to 1.31.3 and for some reason it all works correctly now on the exact same version...

Anyway thanks for the quick response! And yes i have all major expansions.

I'm really confused why it's suddenly working haha. Sorry for wasting your time!

Update:

I was making a mod for EU4 and its possible i might accidently changed some files in EU4 itself rather than changing it in my mod folder. That would then change the checksum and maybe screw around with the console patcher? I did reinstall the latest version and it worked after that. its the only explanation I can think of.

Anyway thanks again for your time and for making this tool! I really appreciate it!

**Comment by steeno** [comment]
@NLangeweg : Ah good to hear, because 1.31.3 worked fine on my end just now and the pattern also only matched one address so the signature seems to be fine. Either way. If it breaks again in the future just tell me and i will look into it again properly. Good luck in your next run =)
