### ISSUE TITLE
I'm having trouble creating the .exe and building.

### ISSUE THREAD

**Issue by RarePossum** [steeno/EU4ConsolePatcher#2]
Apologies for my inexperience, but could you say, record a video of how to build. I've experimented with code but never actually built anything. When I try to build it, it has an error saying the Windows SDK version could not be found or something. That I don't have version. 10.0.17134.0

**Comment by steeno** [comment]
Hi RarePossum,
don't hesitate to ask questions. The explanation in the README is far from great and complete. 
I assume that there is a mismatch between the installed Windows SDK version on your system and the WindowsTargetPlatformVersion parameter in the project file. I thought that Visual Studio would inform the user to update the project if the currently set Windows SDK version is not available on the system. Are you using Visual Studio or just msbuild to compile the project?

If you are using Visual Studio, you could open the solution file, right click on the `EU4ConsolePatcher` project, select `Properties`, navigate to `Configuration Properties -> General` and select a proper `Windows SDK Version` on the right side and try to build the project again.

![devenv_Yp2eUFkJqq](https://user-images.githubusercontent.com/1254034/54381621-860fe600-468e-11e9-9451-4ae002b35d95.png)

If this does not help it would be nice to know how you tried to build the project.

**Comment by RarePossum** [comment]
Thank you, that worked. However, I can't find `nmake release` or `nmake debug`. Any help on that?

**Comment by steeno** [comment]
Have you installed the VC++ compiler and libs package in Visual Studio? Open Visual Studio, open `Tools -> Get Tools and Features...` in the top menu bar.

![devenv_1VWHACpMdm](https://user-images.githubusercontent.com/1254034/54467617-97d4b480-4786-11e9-9f56-6a1641e1114c.png)

A new Dialog should appear. Select `Single components` in this new window, scroll down to `Compiler, build tools and runtimes` and select one of the `VC++ toolset` versions listed there and click on change. Unfortunately i can only other a screen of the german version.

![vs_installershell_EQscRjyM3C](https://user-images.githubusercontent.com/1254034/54467618-999e7800-4786-11e9-99e9-266f3dc34a21.png)

If this still does not help, just select `Desktop development with c++` in the workloads section. 

![vs_installershell_WbiPeFudMR](https://user-images.githubusercontent.com/1254034/54467662-ebdf9900-4786-11e9-9b8d-63b8a34d9906.png)

And finally after opening the project in Visual Studio, just right click on the project and click on build.

![devenv_JoiIAo0kBg](https://user-images.githubusercontent.com/1254034/54467707-28ab9000-4787-11e9-9696-0d25cdad454c.png)

EDIT: You don't need to do the cmdline steps, you can just use Visual Studio directly to build the project. The cmdline instructions are just an alternative for people which may have installed the build tools but not VS.

**Comment by RarePossum** [comment]
I have now managed to build it, thanks to you, but I can't find the .exe Can you help with that?

**Comment by steeno** [comment]
It depends on the build configuration. So f.e. if you have chosen `Release / x64` you should find a `x64/Release` folder in the project folder with the compiled .exe in it.

![devenv_scthAiePte](https://user-images.githubusercontent.com/1254034/54472147-06843300-47c4-11e9-9cc2-9edb956b65ce.png)
![explorer_1X29s0HXFE](https://user-images.githubusercontent.com/1254034/54472157-274c8880-47c4-11e9-8b52-6a0260b4fcdc.png)

**Comment by RarePossum** [comment]
Thank you so much. It worked.
