### ISSUE TITLE
Reduces in-game framerates.

### ISSUE THREAD

**Issue by kuccygang** [steeno/EU4ConsolePatcher#3]
When the script is enabled, unpausing the game makes it lag so much that you can't even click stuff. N

**Comment by steeno** [comment]
Sorry to hear that, haven't tried it now, EU4 currently not installed.
At least the last time i tried it after the release of golden century everything worked fine, couldn't directly discover any performance differences.
So you start a ironman game session, pause the game, tab to windows, start the application (which version?), tab back to game, unpause, instant lag? The application closes and you don't get any errors in the console output? You could try one of the debug releases, there is more console output which you could also paste in your next comment.

**Comment by kuccygang** [comment]
No errors, no crashes. Just low game performance. Didn't try anything.
Gonna try a debug release tomorrow.

**Comment by steeno** [comment]
@kuccygang could you check if the new version 1.0.4.2 in combination with the 1.29 game update runs better on your system?

**Comment by kuccygang** [comment]
Yeah sure I can test it tomorrow.

**Comment by kuccygang** [comment]
Sorry for the late reply. I was unable to use it in 1.29 when I tried it today. Just tried the new release and it works fine. Performance drops are gone as far as i can see. Thanks for the release!

**Comment by kuccygang** [comment]
Ok the game performance is still dropped by a little bit but it's playable.
