### ISSUE TITLE
Not working with 1.29

### ISSUE THREAD

**Issue by Umnumas** [steeno/EU4ConsolePatcher#4]
Hey buddy, with the 1.29 update ( updated eu4 to 64 bit) this doesnt work anymore. Might be something different but i suppose that it is this. Would be awesome if you would take the time to fix this again.

**Comment by steeno** [comment]
Hey bro, will probably take a look tomorrow, thanks for the compatibility update.

**Comment by ArneDeGeeter** [comment]
Just a  small update, as I was trying to use this for the first time, this is the error that is given in the console. 
```Trying to enable debug privileges for the current process
Debug privileges enabled
Trying to find process eu4.exe
eu4.exe process found
Trying to find module eu4.exe
eu4.exe module found
Trying to find memory patterns
First memory pattern could not be found


```

**Comment by ghost** [comment]
Got the new update, but it's still either not finding the module, or it's finding the module and not finding the memory patterns.

**Comment by steeno** [comment]
@Andredie : I haven't released an update yet xD Will be available in the next hour or two.
@Dark-Xiphles : Thanks for the console output. I am aware of the problem, analyzed it yesterday already, will release an update in the next 1-2 hours.
Have you guys discovered any performance increases in 1.29? Haven't checked the changelog yet but at least they have switched to a 64bit release now.

**Comment by Umnumas** [comment]
With my setup i didnt had any ingame problems anyway, but the loading time is soooo much faster. Im doing a very crazy strategy right now and have to ALT + F4 all the time and every loading is a few seconds faster ( ofc with SSD). However for many people the launcher is bugged, and some have bugs like really tiny UI windows, but i think thats the smallest amount.

**Comment by steeno** [comment]
Hmm, sounds nice so far. I think i will watch/read the last 3 new dev diaries since the spain update. This should be enough to get me fired up again :D
Update is live https://github.com/steeno/EU4ConsolePatcher/releases/tag/v1.0.4.2
Keep me up2date if it works or not 👍

**Comment by ghost** [comment]
@steeno My apoligies, I'm an idiot, saw the latest release was September 18th, and thought "Oh, that was quick", didn't see till now that it was September 18th 2018 hahahah

**Comment by steeno** [comment]
@Andredie xD so at least the last version worked almost 1year 💪 
Have you tried v1.0.4.2 yet?

**Comment by ghost** [comment]
@steeno I have, works perfectly, the performace issues are even gone, but that might have had something to do with the game update, even though the patcher seemed to make the performace somewhat worse in the last version

**Comment by steeno** [comment]
ok so you mention the same behaviour as kuccygang in the other open issue. even so he claimed extreme performance issues with the patcher ^^ maybe this release, including the game update itself, will help him too.
nethertheless thanks for the feedback 👍

**Comment by ghost** [comment]
@steeno Well I'd rarely call it extreme, but it was pretty bad at times, worst I experienced was hitting pause for the first of the month and the game just running till after the 20th before registering it, but normally it was just generally kinda laggy

**Comment by 00jacket** [comment]
@steeno good shit man appreciate it

**Comment by Umnumas** [comment]
wow thanks @steeno if you ever want to come back to eu4 or just talk add me on discord LaZzy
#4395

**Comment by yiguanyu1997** [comment]
Well,can you ADD IR and Stellaris supports? @steeno

**Comment by steeno** [comment]
@yiguanyu1997 noted the request. But i have to admit that i am not super duper skilled in regards of reverse engineering, so i can't promise anything. The eu4 part was rather simple. But at least i am currently relatively motivated in this case, so maybe there will smth. available in the near future.

**Comment by yiguanyu1997** [comment]
> @ yiguanyu1997注意到了该请求。但是我必须承认，我在逆向工程方面不是超级骗子，所以我什么都不能保证。eu4部分非常简单。但是至少在这种情况下，我目前相对比较有动力，所以也许会有很多。在不久的将来可用。

OK，I know what you faced problems,becaue i can't also know about the thing.But I must thank you for your contribution.
