### ISSUE TITLE
Patcher closes the game and removes EU4ConsolePatcher.exe from the folder

### ISSUE THREAD

**Issue by Patresss** [steeno/EU4ConsolePatcher#5]
Patcher closes the game and removes EU4ConsolePatcher.exe from the folder. What is more, I cannot again paste EU4ConsolePatcher.exe to steamapps\common\Europa Universalis IV "Access Denied"

**Comment by steeno** [comment]
You don't need to copy the .exe to your steam folder. You can start it wherever you want.
If the .exe gets removed it sounds more like an antivirus issue to me, so it detects the tool as malware and removes it, can you check your av log?
Just tested the latest release with the 1.29.2 hotfix of eu4 and it works at least on my machine, so no crash to desktop of the game or so.

**Comment by Patresss** [comment]
> Just tested the latest release with the 1.29.2 hotfix of eu4 and it works at least on my machine, so no crash to desktop of the game or so.

This is weird. I've never had this problem before. When I run EU4ConsolePatcher.exe It closes the game
I use 1.29.2.0 version.

**Comment by steeno** [comment]
@Patresss could you try the https://github.com/steeno/EU4ConsolePatcher/releases/download/v1.0.4.2/EU4ConsolePatcher-Debug-x64-static-v1.0.4.2.zip debug release and paste the cmdline output here?

**Comment by Patresss** [comment]
@steeno but I think that you are right. I closed the antivirus (avast) and it works! Thanks and sorry for the problem!
