### ISSUE TITLE
I don't find an exe file?

### ISSUE THREAD

**Issue by ghost** [steeno/EU4ConsolePatcher#7]
I downloaded your code and file, but I can't find an exe file.

**Comment by steeno** [comment]
Most likely removed by your antivirus software. File may get viewed as malicious because it contains basic usage of methods to alter foreign processes like diverse malware. So you may need to exclude the archive from your antivirus or use the cheatengine table instead.

**Comment by ghost** [comment]
Am I supposed to convert the sln file into an exe? Because i dont see an exe file in the code area either.

**Comment by steeno** [comment]
You have to download one of the zip files in the release section. But as i said, the .exe file inside this .zip archives gets deleted from your antivirus software. You can also download visual studio 2017/2019 community edition and try to compile the binary yourself as stated in the readme.

**Comment by ghost** [comment]
Thanks! It worked, anti virus didnt trigger either.
